app:
  port: 8092
  host: "0.0.0.0"
  thread_pool: 5
  log_level: "INFO"
service:
  protosvg_address: "localhost:50051"
  font_dir: "/usr/share/fonts"
  gan_weights: "/inference-api/weights/covergan.pt"
  captioner_weights: "/inference-api/weights/captioner.pt"
